# This is the generic makefile that could be used by every system
# to install all files in development directory required by ioc

#Pre installation
#ioc ::

#install ::

#Post installation
ioc ::
	slsinstall -V -a
#install ::
#	@echo "insert here your post installation commands"
